<#
.SYNOPSIS
  Generates a strongly-typed C# accessor class from Strings.resx (the neutral/English
  string catalog), mirroring what Visual Studio's ResXFileCodeGenerator produces —
  but callable from plain `dotnet build` / build.bat with no IDE dependency.

  Run automatically as an MSBuild target (see QuickMail.csproj) before CoreCompile
  whenever Strings.resx is newer than Strings.Designer.cs. Only the neutral resx
  drives the generated class; per-language Strings.<culture>.resx files are satellite
  resources only and never generate code.
#>
param(
    [Parameter(Mandatory = $true)][string]$ResxPath,
    [Parameter(Mandatory = $true)][string]$OutputPath
)

$ErrorActionPreference = 'Stop'

[xml]$resx = Get-Content -Path $ResxPath -Raw

$keys = @()
foreach ($node in $resx.root.data) {
    $name = $node.name
    if ([string]::IsNullOrWhiteSpace($name)) { continue }
    if ($name -notmatch '^[A-Za-z_][A-Za-z0-9_]*$') {
        throw "Resource key '$name' is not a valid C# identifier. Keys must match [A-Za-z_][A-Za-z0-9_]*."
    }
    $keys += $name
}

$keys = $keys | Sort-Object -Unique

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('// <auto-generated>')
[void]$sb.AppendLine('// Generated by scripts/Generate-ResxDesigner.ps1 from Resources/Strings.resx.')
[void]$sb.AppendLine('// Do not edit by hand — edit Strings.resx and rebuild.')
[void]$sb.AppendLine('// </auto-generated>')
[void]$sb.AppendLine('#nullable enable')
[void]$sb.AppendLine('using System.Globalization;')
[void]$sb.AppendLine('using System.Resources;')
[void]$sb.AppendLine()
[void]$sb.AppendLine('namespace QuickMail.Resources;')
[void]$sb.AppendLine()
[void]$sb.AppendLine('/// <summary>Strongly-typed accessor over Strings.resx. Missing keys are a build error, not a silent blank.</summary>')
[void]$sb.AppendLine('public static class Strings')
[void]$sb.AppendLine('{')
[void]$sb.AppendLine('    private static readonly ResourceManager _resourceManager =')
[void]$sb.AppendLine('        new("QuickMail.Resources.Strings", typeof(Strings).Assembly);')
[void]$sb.AppendLine()
[void]$sb.AppendLine('    public static ResourceManager ResourceManager => _resourceManager;')
[void]$sb.AppendLine()
[void]$sb.AppendLine('    /// <summary>Overrides the culture used to resolve strings. Null (default) = CultureInfo.CurrentUICulture.</summary>')
[void]$sb.AppendLine('    public static CultureInfo? Culture { get; set; }')
[void]$sb.AppendLine()

foreach ($key in $keys) {
    [void]$sb.AppendLine("    public static string $key => _resourceManager.GetString(`"$key`", Culture) ?? string.Empty;")
}

[void]$sb.AppendLine('}')

$content = $sb.ToString()
$existing = if (Test-Path $OutputPath) { Get-Content -Path $OutputPath -Raw } else { $null }
if ($existing -ne $content) {
    Set-Content -Path $OutputPath -Value $content -NoNewline -Encoding utf8
    Write-Host "Generated $OutputPath ($($keys.Count) keys)"
} else {
    # Content is already correct, but MSBuild's Inputs/Outputs staleness check compares
    # raw file timestamps — a git checkout/rebase/clone touches all files at nearly the
    # same instant with no guaranteed relative ordering, so Strings.resx can end up
    # "newer" than this file forever after even though nothing needs regenerating. Bump
    # the timestamp forward so the next build's Inputs/Outputs check correctly sees this
    # file as up to date and skips re-invoking this script entirely.
    (Get-Item -Path $OutputPath).LastWriteTime = Get-Date
    Write-Host "Strings.Designer.cs up to date ($($keys.Count) keys)"
}
